version: '3.7'

# Creating our network
networks:
    webserver:

# Creating volumes for persistence
volumes:
    www:
    ps_cache:
    nginx:
    _data:
    sock:

# Defining our services
services:
    mysql:
        # Install MYSQL 8
        image: 'mysql:latest'
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        ports:
            - "3306:3306"
        volumes:
            - _data:/var/lib/mysql
        networks:
            - webserver

    php:
        # Install PHP7.4-FPM
        build: './php-fpm'
        container_name: php
        restart: always
        volumes:
            - sock:/sock
            - www:/var/www/html 
        networks:
            - webserver

    nginx:
        # Compile Nginx
        build: './nginx'
        container_name: nginx
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - www:/var/www/html
            - nginx:/etc/nginx
            - ps_cache:/var/cache/ngx_pagespeed
            - sock:/sock
        networks:
            - webserver
